## items to fill in
#
# LANDSCAPENAME - your landscape name as it should be displayed ( i.e. 'OSPO Landscape' )
# LANDSCAPESHORTNAME - your landscape name in a short version ( i.e. 'OSPO' )
# PROJECTNAME - the project's name ( i.e. 'TODO Group' )
# DOMAINNAME - the project's domain name ( i.e. 'todogroup.org' )
# PROJECTTWITTER
# PROJECTGITHUB - don't include the https://github.com part - just the org and the repo ( i.e. cncf/ospolandscape )
# PROJECTCRUNCHBASE - https://www.crunchbase.com/organization/XXXXX ( XXXX would be specific to the project on Crunchbase )

global:
  # name of the landscape
  name: Tazama Project Landscape
  # shortname
  short_name: Tazama
  # repo where this landscape is hosted ( minus the https://github.com part )
  repo: tazama-lf/tazama-landscape-v1
  # URL to the landscape
  website: https://landscape.tazama.org
  # Short domain name for the landscape (usually this would change 'l' for 'landscape'
  short_domain: l.tazama.org
  # Your project's website
  company_url: https://tazama.org
  # General contact email for the landscape
  email: info@tazama.org
  # Crunchbase entry for your project - fill in 
  self: https://www.crunchbase.com/organization/tazama-project
  meta:
    # Should match name above
    title: Tazama Project Landscape
    # keep this
    fb_admin: alex.contini.94
    # site description
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    # your project's twitter
    twitter: '@TazamaOrg'
    # update if needed
    google_site_verification: QoKVWoKBgDtyXTeg4NlXtx3q2YP7NjVDFvtlPURt22Q
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  # Category for members
  membership: Tazama Project Participants
  # Update for the categories where you won't be showing the open source license ( typically done for members or conformance program members )
  flags:
    hide_license_for_categories:
      - Tazama Project Participants
# Data for the twitter card
twitter:
  search: landscape.tazama.org
  url: https://landscape.tazama.org
  text: Tazama Project's Ecosystem Landscape 
# Complete this section for identifying hosted projects of your project, along with member projects
relation:
  label: Tazama Project Relation
  url: tazama
  values:
    - id: hosted
      label: Tazama Projects
      # children to identify maturity levels ( incubation, active, etc ). If there aren't multiple levels, then just complete like below.
      children:
        - id: foundationproject
          label: Tazama Project Child Projects
          prefix: Tazama Project
          tag: Foundation Project
          color: '#50BE99'
          big_picture_order: 1
          big_picture_label: Tazama Project Project
          big_picture_color: rgb(80,190,153)
    - id: company
      label: Tazama Project Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: Tazama Project Member Products/Projects
      tag: Tazama Project Member
    - id: false
      label: Non-Tazama Project Member Products/Projects
      url: 'no'
# membership levels
membership:
  # category for project members
  #General:
    #name: Tazama Project
    #label: Member
    #funding: General
  # category for LF members
  System Integrators:
    name: Tazama Project
    label: SI
    funding: None
  Consulting / Staffing Firms:
    name: Tazama Project
    label: Con
    funding: None
  Systems Integrators:
    name: Tazama Project
    label: SI
    funding: None
  Consulting / Staffing Firms:
    name: Tazama Project
    label: Con
    funding: None
  # category for LF members
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation Charities
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  # update to change the header text
  header: >
    <h1>Tazama Project Landscape</h1> The Tazama Project Landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  # don't change this
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
# ads for the landscape. Good opportunity to advertise your project events
ads:
  - url: https://tazama.org/contact/calendar/
    image: /images/cal-iocn.svg
    title: Tazama Community Calendar
# preset searches
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
# sets the rendering of the landscape
big_picture:
  # this is for the main page
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Tazama Project Landscape
    fullscreen_header: See the interactive landscape at l.tazama.org
    # add one element for each category in landscape.yml
    elements:
      - type: HorizontalCategory
        category: Tazama Project Participants
        rows: 4
        width: 650
        height: 150
        top: 210
        left: 0
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Tazama Project Adopters
        rows: 4
        width: 650
        height: 150
        top: 210
        left: 0
        color: rgb(165,9,77)
        fit_width: true       
      - type: HorizontalCategory
        category: Tazama Project Funders
        rows: 4
        width: 650
        height: 150
        top: 210
        left: 0
        color: rgb(47,116,190)
        fit_width: true
      - type: HorizontalCategory
        category: Related Organizations
        rows: 4
        width: 650
        height: 150
        top: 210
        left: 0
        color: rgb(0,0,0)
        fit_width: true              
      # this is a landscape info box; good idea to keep this one
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 210
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Tazama Project community, and also shows the participating organizations of the Tazama Project.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.tazama.org
            top: 95
            left: 10
            font_size: 18
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: Tazama Project Logo
# test to make sure the build worked. Identify one landscape item that you know will always be there, preferably towards the top of the rendering
test:
  header: Tazama Project Landscape TEST
  section: Tazama Project Participants
  logo: left-logo.svg # pick any logo to put here
# if you have a common view, create a pre-render to speed the render time up
prerender:
  # good pre-render to always have; embedable member logo list for a website. Renders to /pages/members
  members: /card-mode?category=open-mainframe-project-member-company&grouping=category&embed=yes&style=borderless
